spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: active

server:
  port: 8888

security:
  user:
    password: ${CONFIG_SERVICE_PASSWORD}
