version: "3"
networks:
    my-mongo-cluster:

services:
  mongo1:
      image: mongo:3.6
      command: mongod --replSet rs0 --port 27018
      ports:
        - 27018:27018
      networks:
        - my-mongo-cluster

  mongo2:
      image: mongo:3.6
      command: mongod --replSet rs0 --port 27019
      ports:
        - 27019:27019
      networks:
        - my-mongo-cluster

  mongo3:
      image: mongo:3.6
      command: mongod --replSet rs0 --port 27020
      ports:
        - 27020:27020
      networks:
        - my-mongo-cluster


  order_service:
      container_name: order_service
      environment:
        SERVER_PORT: 8081
        URI: mongodb://mongo1:27018,mongo2:27019,mongo3:27020/orders?replicaSet=rs0
      expose:
       - 8081
      ports:
       - 8081:8081
      healthcheck:
         test: ["CMD", "curl", "-f", "http://localhost:8081"]
         interval: 30s
         timeout: 10s
         retries: 5
      image: order_service:latest
      build:
        context: ./
        dockerfile: Dockerfile
      restart: always
      networks:
        - my-mongo-cluster