kind: Service
apiVersion: v1
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  selector:
    role: mongodb
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
---
kind: Service
apiVersion: v1
metadata:
  name: orderservice
spec:
  selector:
    app: orderservice
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP

