server:
  port: 8085

spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: root
    jpa:
        hibernate.ddl-auto: update
        generate-ddl: true
        show-sql: true
        properties:
           hibernate:
             dialect: org.hibernate.dialect.MySQL8Dialect
             naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
